-- 0001_baseline_schema.sql — DB-M1
-- PostgreSQL-native equivalent of the authoritative A3 SQLite schema (63 tables
-- + sessions). Derived by tools/dbm1/gen-pg-schema.js from the REAL SQLite
-- schema, then reviewed. Type policy (docs/DATABASE_ARCHITECTURE.md):
--   SQLite INTEGER -> BIGINT (64-bit, lossless: money in sen, bp, minutes, ids, 0/1 flags)
--   business dates -> DATE            (rendered to the app as 'YYYY-MM-DD')
--   event/audit timestamps -> TIMESTAMPTZ (rendered as UTC 'YYYY-MM-DD HH:MM:SS')
--   REAL (3 legacy display-hour columns) -> DOUBLE PRECISION; minutes stay authoritative
-- Tables are created in dependency-safe order computed from the actual foreign keys.

-- Parity with SQLite datetime('now'): statement-time, UTC, whole seconds.
CREATE FUNCTION kahe_now() RETURNS timestamptz LANGUAGE sql VOLATILE AS
$$ SELECT date_trunc('second', clock_timestamp()) $$;

-- Parity with SQLite date(x, '<n> day') used by effective-date supersession.
CREATE FUNCTION kahe_date_add(d date, days integer) RETURNS date LANGUAGE sql IMMUTABLE AS
$$ SELECT d + days $$;

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  description TEXT
);

CREATE TABLE role_permissions (
  role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  action TEXT NOT NULL DEFAULT 'VIEW',
  PRIMARY KEY (role_id, permission_id, action)
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  display_name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT kahe_now()
);

CREATE TABLE user_roles (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  location TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE legal_entities (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('internal','subkontraktor')),
  npwp TEXT,
  jkk_risk_class TEXT NOT NULL CHECK (jkk_risk_class IN ('very_low','low','medium','high','very_high')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  effective_date DATE NOT NULL,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now(),
  updated_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  legal_entity_id TEXT REFERENCES legal_entities(id),
  npwp TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE worker_service_addons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addon_type TEXT NOT NULL CHECK (addon_type IN ('TRANSPORT','MEALS','ACCOMMODATION')),
  enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)),
  delivery_mode TEXT NOT NULL,
  employee_entitlement TEXT NOT NULL DEFAULT 'ENTITLED' CHECK (employee_entitlement IN ('ENTITLED','NOT_ENTITLED','OPTIONAL')),
  client_billable BIGINT NOT NULL DEFAULT 0 CHECK (client_billable IN (0,1)),
  client_billable_mode TEXT NOT NULL DEFAULT 'NO' CHECK (client_billable_mode IN ('YES','NO','CONDITIONAL')),
  billable_condition TEXT,
  cost_bearer TEXT NOT NULL DEFAULT 'NOT_APPLICABLE' CHECK (cost_bearer IN ('CLIENT','KAHE','SHARED','THIRD_PARTY','NOT_APPLICABLE')),
  cost_share_kahe_bp BIGINT,
  billing_treatment TEXT NOT NULL DEFAULT 'NON_BILLABLE' CHECK (billing_treatment IN ('SEPARATE','BUNDLED','NON_BILLABLE')),
  quantity_basis TEXT NOT NULL DEFAULT 'NOT_APPLICABLE' CHECK (quantity_basis IN ('PER_WORKER_PER_DAY','PER_WORKER_PER_MONTH', 'PER_WORKER_PER_TRIP','PER_ATTENDANCE_DAY','PER_HEADCOUNT','FLAT','NOT_APPLICABLE')),
  rate_sen BIGINT CHECK (rate_sen IS NULL OR rate_sen >= 0),
  payroll_component_code TEXT,
  legal_entity_id TEXT NOT NULL REFERENCES legal_entities(id),
  client_id BIGINT REFERENCES clients(id),
  project_id BIGINT REFERENCES projects(id),
  version BIGINT NOT NULL DEFAULT 1,
  effective_from DATE NOT NULL,
  effective_to DATE,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ACTIVE','SUPERSEDED','CANCELLED')),
  note TEXT,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  approved_by TEXT,
  approved_at TIMESTAMPTZ
);

CREATE TABLE worker_service_addon_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addon_id BIGINT NOT NULL REFERENCES worker_service_addons(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  actor TEXT NOT NULL,
  before_json TEXT,
  after_json TEXT,
  note TEXT,
  occurred_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE billing_rate_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addon_type TEXT NOT NULL CHECK (addon_type IN ('TRANSPORT','MEALS','ACCOMMODATION','PAYROLL_COST','SERVICE_FEE')),
  meal_type TEXT,
  pricing_model TEXT NOT NULL,
  quantity_source TEXT NOT NULL DEFAULT 'NOT_APPLICABLE',
  unit_of_measure TEXT NOT NULL DEFAULT 'UNIT',
  rate_sen BIGINT CHECK (rate_sen IS NULL OR rate_sen >= 0),
  rate_status TEXT NOT NULL DEFAULT 'NOT_CONFIGURED' CHECK (rate_status IN ('NOT_CONFIGURED','CONFIGURED')),
  payroll_basis TEXT,
  legal_entity_id TEXT NOT NULL REFERENCES legal_entities(id),
  client_id BIGINT REFERENCES clients(id),
  project_id BIGINT REFERENCES projects(id),
  version BIGINT NOT NULL DEFAULT 1,
  effective_from DATE NOT NULL,
  effective_to DATE,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ACTIVE','SUPERSEDED','CANCELLED')),
  note TEXT,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  approved_by TEXT,
  approved_at TIMESTAMPTZ
);

CREATE TABLE meal_plan_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meal_type TEXT NOT NULL,
  enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)),
  planned_entitlement TEXT NOT NULL DEFAULT 'ENTITLED' CHECK (planned_entitlement IN ('ENTITLED','NOT_ENTITLED','OPTIONAL')),
  max_per_worker_per_day BIGINT,
  note TEXT,
  legal_entity_id TEXT NOT NULL REFERENCES legal_entities(id),
  client_id BIGINT REFERENCES clients(id),
  project_id BIGINT REFERENCES projects(id),
  version BIGINT NOT NULL DEFAULT 1,
  effective_from DATE NOT NULL,
  effective_to DATE,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ACTIVE','SUPERSEDED','CANCELLED')),
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  approved_by TEXT,
  approved_at TIMESTAMPTZ
);

CREATE TABLE employees (
  id TEXT PRIMARY KEY,
  full_name TEXT NOT NULL,
  nik TEXT,
  photo_path TEXT,
  birth_date DATE,
  gender TEXT CHECK (gender IN ('L','P')),
  phone TEXT,
  address TEXT,
  worker_type TEXT NOT NULL CHECK (worker_type IN ('internal','pkwt','harian','subkontraktor')),
  project_code TEXT REFERENCES projects(code),
  position TEXT,
  supervisor TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  start_date DATE,
  termination_date DATE,
  bpjs_kesehatan_no TEXT,
  bpjs_tk_no TEXT,
  bank_name TEXT,
  bank_account_no TEXT,
  bank_account_name TEXT,
  nip TEXT,
  grade TEXT,
  permanent_date DATE,
  contract_no TEXT,
  contract_start DATE,
  contract_end DATE,
  wage_scheme TEXT,
  daily_rate_sen BIGINT,
  pay_cycle TEXT CHECK (pay_cycle IS NULL OR pay_cycle IN ('mingguan','dua_mingguan','bulanan')),
  partner_company TEXT,
  partner_npwp TEXT,
  partner_pic TEXT,
  pks_no TEXT,
  work_scope TEXT,
  worker_count BIGINT,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now(),
  updated_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE billing_quantities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legal_entity_id TEXT NOT NULL REFERENCES legal_entities(id),
  client_id BIGINT REFERENCES clients(id),
  project_id BIGINT REFERENCES projects(id),
  addon_id BIGINT REFERENCES worker_service_addons(id),
  addon_type TEXT NOT NULL CHECK (addon_type IN ('TRANSPORT','MEALS','ACCOMMODATION')),
  meal_type TEXT,
  billing_period TEXT NOT NULL,
  employee_id TEXT REFERENCES employees(id),
  service_date DATE,
  service_period_start DATE,
  service_period_end DATE,
  quantity_source TEXT NOT NULL,
  quantity BIGINT NOT NULL,
  unit_of_measure TEXT NOT NULL,
  source_reference TEXT,
  verification_status TEXT NOT NULL DEFAULT 'UNVERIFIED' CHECK (verification_status IN ('UNVERIFIED','VERIFIED','REJECTED','SUPERSEDED')),
  verified_by TEXT,
  verified_at TIMESTAMPTZ,
  rejection_reason TEXT,
  version BIGINT NOT NULL DEFAULT 1,
  corrects_quantity_id BIGINT REFERENCES billing_quantities(id),
  adjustment_reason TEXT,
  is_adjustment BIGINT NOT NULL DEFAULT 0 CHECK (is_adjustment IN (0,1)),
  route_id TEXT,
  vehicle_id TEXT,
  vehicle_type TEXT,
  shift_id TEXT,
  pickup_point TEXT,
  drop_point TEXT,
  trip_reference TEXT,
  operator_reference TEXT,
  billed_in_run_id BIGINT,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE billing_quantity_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quantity_id BIGINT NOT NULL REFERENCES billing_quantities(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  actor TEXT NOT NULL,
  before_json TEXT,
  after_json TEXT,
  note TEXT,
  occurred_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE billing_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_reference TEXT NOT NULL UNIQUE,
  legal_entity_id TEXT NOT NULL REFERENCES legal_entities(id),
  client_id BIGINT NOT NULL REFERENCES clients(id),
  project_id BIGINT REFERENCES projects(id),
  billing_period TEXT NOT NULL,
  run_number BIGINT NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','CALCULATED','CANCELLED')),
  total_amount_sen BIGINT NOT NULL DEFAULT 0,
  line_count BIGINT NOT NULL DEFAULT 0,
  calculation_timestamp TIMESTAMPTZ,
  engine_version TEXT,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  cancelled_by TEXT,
  cancelled_at TIMESTAMPTZ,
  cancel_reason TEXT,
  UNIQUE (legal_entity_id, client_id, billing_period, run_number)
);

CREATE TABLE billing_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  billing_run_id BIGINT NOT NULL REFERENCES billing_runs(id) ON DELETE CASCADE,
  legal_entity_id TEXT NOT NULL,
  client_id BIGINT NOT NULL,
  project_id BIGINT,
  billing_period TEXT NOT NULL,
  source_type TEXT NOT NULL,
  source_reference TEXT,
  addon_type TEXT NOT NULL,
  meal_type TEXT,
  delivery_mode TEXT,
  pricing_model TEXT NOT NULL,
  quantity_source TEXT,
  quantity BIGINT,
  unit_of_measure TEXT,
  effective_rate_sen BIGINT,
  amount_sen BIGINT NOT NULL,
  cost_bearer TEXT NOT NULL,
  billing_treatment TEXT NOT NULL,
  addon_config_version BIGINT,
  addon_config_id BIGINT,
  rate_version BIGINT,
  rate_card_id BIGINT,
  quantity_ids TEXT,
  verified_by TEXT,
  calculation_note TEXT,
  calculation_timestamp TIMESTAMPTZ NOT NULL
);

CREATE TABLE service_fee_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legal_entity_id TEXT NOT NULL REFERENCES legal_entities(id),
  client_id BIGINT REFERENCES clients(id),
  project_id BIGINT REFERENCES projects(id),
  fee_mode TEXT NOT NULL DEFAULT 'NOT_CONFIGURED' CHECK (fee_mode IN ('NOT_CONFIGURED','PERCENTAGE','FIXED_PER_WORKER','FIXED_PER_MONTH')),
  fee_rate_bp BIGINT,
  fee_amount_sen BIGINT,
  fee_basis TEXT,
  version BIGINT NOT NULL DEFAULT 1,
  effective_from DATE NOT NULL,
  effective_to DATE,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ACTIVE','SUPERSEDED','CANCELLED')),
  note TEXT,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  approved_by TEXT,
  approved_at TIMESTAMPTZ
);

CREATE TABLE user_legal_entity_scope (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  legal_entity_id TEXT NOT NULL REFERENCES legal_entities(id),
  granted_by TEXT,
  granted_at TIMESTAMPTZ DEFAULT kahe_now(),
  note TEXT,
  PRIMARY KEY (user_id, legal_entity_id)
);

CREATE TABLE entity_access_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  actor TEXT NOT NULL,
  outcome TEXT NOT NULL CHECK (outcome IN ('DENIED','OVERRIDE_ALLOWED')),
  resource_type TEXT NOT NULL,
  resource_id TEXT,
  requested_entity TEXT,
  authorized_scope TEXT,
  route TEXT,
  occurred_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE user_project_scope (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  project_code TEXT NOT NULL,
  PRIMARY KEY (user_id, project_code)
);

CREATE TABLE audit_auth_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  email TEXT,
  user_id BIGINT,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT kahe_now()
);

CREATE TABLE employee_contract_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  contract_no TEXT,
  start_date DATE,
  end_date DATE,
  renewal_number BIGINT DEFAULT 0,
  action TEXT NOT NULL CHECK (action IN ('new','extend','terminate')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  requested_by TEXT,
  approved_by TEXT,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now(),
  decided_at TIMESTAMPTZ
);

CREATE TABLE employee_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  doc_type TEXT NOT NULL CHECK (doc_type IN ('ktp','ijazah','sertifikat','lainnya')),
  doc_name TEXT,
  file_path TEXT NOT NULL,
  expiry_date DATE,
  uploaded_by TEXT,
  uploaded_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE timesheet_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  work_date DATE NOT NULL,
  workfront TEXT,
  shift TEXT CHECK (shift IS NULL OR shift IN ('day','night')),
  clock_in TEXT,
  clock_out TEXT,
  work_hours DOUBLE PRECISION,
  work_minutes BIGINT,
  attendance_status TEXT NOT NULL DEFAULT 'present' CHECK (attendance_status IN ('present','late','absent','leave','sick','no_show')),
  absence_reason TEXT,
  overtime_hours_requested DOUBLE PRECISION DEFAULT 0,
  overtime_hours_approved DOUBLE PRECISION DEFAULT 0,
  overtime_minutes_requested BIGINT DEFAULT 0,
  overtime_minutes_approved BIGINT DEFAULT 0,
  overtime_status TEXT NOT NULL DEFAULT 'none' CHECK (overtime_status IN ('none','pending','approved','rejected')),
  overtime_requested_by TEXT,
  overtime_approved_by TEXT,
  overtime_decided_at TIMESTAMPTZ,
  day_type TEXT CHECK (day_type IS NULL OR day_type IN ('WORKDAY','WEEKLY_REST_DAY','PUBLIC_HOLIDAY', 'COMPANY_HOLIDAY','SUBSTITUTED_HOLIDAY')),
  day_type_source TEXT,
  day_type_calendar_id BIGINT,
  day_type_pattern_id BIGINT,
  day_classified_at TIMESTAMPTZ,
  note TEXT,
  recorded_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now(),
  updated_at TIMESTAMPTZ DEFAULT kahe_now(),
  legal_entity_id TEXT,
  entry_source TEXT,
  recorded_by_user_id BIGINT,
  updated_by_user_id BIGINT,
  overtime_requested_by_user_id BIGINT,
  overtime_requested_at TIMESTAMPTZ,
  overtime_decided_by_user_id BIGINT,
  work_schedule_id BIGINT,
  work_pattern_def_id BIGINT,
  schedule_code TEXT,
  scheduled_clock_in TEXT,
  scheduled_clock_out TEXT,
  scheduled_minutes BIGINT,
  schedule_cross_midnight BIGINT,
  break_minutes_unpaid BIGINT,
  break_minutes_paid BIGINT,
  day_status TEXT,
  schedule_source TEXT,
  overtime_eligible_from TEXT,
  clock_out_date DATE,
  elapsed_minutes BIGINT,
  late_minutes BIGINT,
  early_leave_minutes BIGINT,
  worked_after_shift_minutes BIGINT,
  schedule_snapshot TEXT,
  record_status TEXT,
  current_version BIGINT,
  last_correction_id BIGINT,
  void_correction_id BIGINT,
  UNIQUE(employee_id, work_date)
);

CREATE TABLE jkk_risk_classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  risk_class TEXT NOT NULL CHECK (risk_class IN ('very_low','low','medium','high','very_high')),
  rate_bp BIGINT NOT NULL,
  effective_date DATE NOT NULL,
  end_date DATE,
  source_note TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE payroll_rule_sets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','superseded')),
  effective_date DATE NOT NULL,
  end_date DATE,
  bpjs_kesehatan_rate_employee_bp BIGINT NOT NULL,
  bpjs_kesehatan_rate_company_bp BIGINT NOT NULL,
  bpjs_kesehatan_salary_cap_sen BIGINT NOT NULL,
  jht_rate_employee_bp BIGINT NOT NULL,
  jht_rate_company_bp BIGINT NOT NULL,
  jp_rate_employee_bp BIGINT NOT NULL,
  jp_rate_company_bp BIGINT NOT NULL,
  jp_salary_cap_sen BIGINT NOT NULL,
  jkm_rate_bp BIGINT NOT NULL,
  overtime_hourly_divisor BIGINT NOT NULL DEFAULT 173,
  overtime_is_taxable BIGINT NOT NULL DEFAULT 1 CHECK (overtime_is_taxable IN (0,1)),
  overtime_is_bpjs_base BIGINT NOT NULL DEFAULT 0 CHECK (overtime_is_bpjs_base IN (0,1)),
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE ptkp_ter_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_set_id BIGINT NOT NULL REFERENCES payroll_rule_sets(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN ('A','B','C')),
  income_min_sen BIGINT NOT NULL,
  income_max_sen BIGINT,
  rate_bp BIGINT NOT NULL
);

CREATE TABLE overtime_multiplier_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_set_id BIGINT NOT NULL REFERENCES payroll_rule_sets(id) ON DELETE CASCADE,
  day_type TEXT NOT NULL CHECK (day_type IN ('workday','rest_or_holiday_5day','rest_or_holiday_6day')),
  hour_from BIGINT NOT NULL,
  hour_to BIGINT,
  multiplier_bp BIGINT NOT NULL
);

CREATE TABLE work_calendars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  legal_entity_id TEXT REFERENCES legal_entities(id),
  project_code TEXT REFERENCES projects(code),
  effective_from DATE NOT NULL,
  effective_to DATE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','superseded')),
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE holidays (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" DATE NOT NULL,
  name TEXT NOT NULL,
  scope TEXT NOT NULL DEFAULT 'national' CHECK (scope IN ('national','project')),
  project_code TEXT,
  holiday_type TEXT NOT NULL DEFAULT 'PUBLIC_HOLIDAY' CHECK (holiday_type IN ('PUBLIC_HOLIDAY','COMPANY_HOLIDAY','SUBSTITUTED_HOLIDAY')),
  work_calendar_id BIGINT REFERENCES work_calendars(id),
  observed_for TEXT,
  is_active BIGINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now(),
  UNIQUE(date, scope, project_code)
);

CREATE TABLE work_patterns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  days_per_week BIGINT NOT NULL CHECK (days_per_week IN (5, 6)),
  weekly_rest_day TEXT NOT NULL DEFAULT 'sunday',
  effective_date DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE payroll_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  legal_entity_id TEXT NOT NULL REFERENCES legal_entities(id),
  project_code TEXT REFERENCES projects(code),
  frequency TEXT NOT NULL DEFAULT 'monthly' CHECK (frequency IN ('monthly','semi_monthly','biweekly','weekly')),
  periods_per_year BIGINT NOT NULL DEFAULT 12,
  work_calendar_id BIGINT REFERENCES work_calendars(id),
  attendance_cutoff_offset_days BIGINT NOT NULL DEFAULT 0,
  overtime_cutoff_offset_days BIGINT NOT NULL DEFAULT 0,
  adjustment_cutoff_offset_days BIGINT NOT NULL DEFAULT 2,
  payment_offset_days BIGINT NOT NULL DEFAULT 5,
  require_warning_acknowledgement BIGINT NOT NULL DEFAULT 1 CHECK (require_warning_acknowledgement IN (0,1)),
  effective_from DATE NOT NULL,
  effective_to DATE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','superseded')),
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE employee_payroll_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  legal_entity_id TEXT NOT NULL REFERENCES legal_entities(id),
  work_pattern_id BIGINT NOT NULL REFERENCES work_patterns(id),
  work_calendar_id BIGINT REFERENCES work_calendars(id),
  payroll_group_id BIGINT REFERENCES payroll_groups(id),
  marital_status TEXT NOT NULL CHECK (marital_status IN ('TK','K')),
  dependents_count BIGINT NOT NULL DEFAULT 0 CHECK (dependents_count BETWEEN 0 AND 3),
  npwp TEXT,
  base_salary_sen BIGINT,
  effective_date DATE NOT NULL,
  end_date DATE,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE config_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain TEXT NOT NULL,
  record_id TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('create','update','delete')),
  changed_by TEXT NOT NULL,
  changed_at TIMESTAMPTZ DEFAULT kahe_now(),
  old_value TEXT,
  new_value TEXT
);

CREATE TABLE salary_components (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  component_type TEXT NOT NULL CHECK (component_type IN ('earning','deduction')),
  calculation_type TEXT NOT NULL CHECK (calculation_type IN ('fixed','variable')),
  paid_by TEXT NOT NULL DEFAULT 'employee' CHECK (paid_by IN ('employee','employer')),
  is_taxable BIGINT NOT NULL DEFAULT 1 CHECK (is_taxable IN (0,1)),
  tax_rule_ref TEXT,
  is_bpjs_base BIGINT NOT NULL DEFAULT 0 CHECK (is_bpjs_base IN (0,1)),
  is_overtime_base BIGINT NOT NULL DEFAULT 0 CHECK (is_overtime_base IN (0,1)),
  is_proratable BIGINT NOT NULL DEFAULT 1 CHECK (is_proratable IN (0,1)),
  recurrence TEXT NOT NULL DEFAULT 'recurring' CHECK (recurrence IN ('recurring','one_time')),
  legal_entity_id TEXT REFERENCES legal_entities(id),
  calculation_order BIGINT NOT NULL DEFAULT 100,
  effective_from DATE NOT NULL,
  effective_to DATE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','superseded')),
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE employee_salary_components (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  component_id BIGINT NOT NULL REFERENCES salary_components(id),
  amount_sen BIGINT NOT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE,
  note TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE payroll_periods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_group_id BIGINT NOT NULL REFERENCES payroll_groups(id),
  period_year BIGINT NOT NULL,
  period_sequence BIGINT NOT NULL,
  period_month BIGINT,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  attendance_cutoff DATE NOT NULL,
  overtime_cutoff DATE NOT NULL,
  adjustment_cutoff DATE NOT NULL,
  payment_date DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','OPEN','CUTOFF','CLOSED')),
  closed_at TIMESTAMPTZ,
  closed_by TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now(),
  CHECK (period_end >= period_start)
);

CREATE TABLE payroll_input_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_period_id BIGINT NOT NULL REFERENCES payroll_periods(id),
  employee_id TEXT NOT NULL REFERENCES employees(id),
  as_of_date DATE NOT NULL,
  legal_entity_id TEXT NOT NULL,
  payroll_group_id BIGINT NOT NULL,
  payroll_group_effective_from DATE,
  assignment_id BIGINT,
  assignment_effective_from DATE,
  work_pattern_id BIGINT,
  work_calendar_id BIGINT,
  work_calendar_effective_from DATE,
  payroll_rule_set_id BIGINT,
  payroll_rule_set_effective_from DATE,
  jkk_risk_class TEXT,
  jkk_rate_version_id BIGINT,
  jkk_rate_effective_from DATE,
  ter_category TEXT,
  resolved_payload TEXT NOT NULL,
  payable_days BIGINT NOT NULL DEFAULT 0,
  period_days BIGINT NOT NULL DEFAULT 0,
  work_minutes_total BIGINT NOT NULL DEFAULT 0,
  overtime_minutes_approved BIGINT NOT NULL DEFAULT 0,
  attendance_row_count BIGINT NOT NULL DEFAULT 0,
  payload_hash TEXT NOT NULL,
  resolution_status TEXT NOT NULL DEFAULT 'OK',
  resolution_errors TEXT,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','FROZEN')),
  resolved_at TIMESTAMPTZ NOT NULL,
  resolved_by TEXT,
  frozen_at TIMESTAMPTZ,
  frozen_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE payroll_exceptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id BIGINT NOT NULL REFERENCES payroll_input_snapshots(id) ON DELETE CASCADE,
  payroll_period_id BIGINT NOT NULL REFERENCES payroll_periods(id),
  employee_id TEXT NOT NULL REFERENCES employees(id),
  legal_entity_id TEXT NOT NULL,
  exception_code TEXT NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('BLOCKING','WARNING','INFORMATIONAL')),
  blocking BIGINT NOT NULL CHECK (blocking IN (0,1)),
  source TEXT NOT NULL,
  message TEXT NOT NULL,
  detail TEXT,
  detected_at TIMESTAMPTZ NOT NULL,
  resolution_status TEXT NOT NULL DEFAULT 'OPEN' CHECK (resolution_status IN ('OPEN','ACKNOWLEDGED','RESOLVED')),
  resolved_by TEXT,
  resolved_at TIMESTAMPTZ,
  resolution_note TEXT
);

CREATE TABLE payroll_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_period_id BIGINT NOT NULL REFERENCES payroll_periods(id),
  legal_entity_id TEXT NOT NULL,
  run_number BIGINT NOT NULL,
  run_type TEXT NOT NULL DEFAULT 'ORIGINAL' CHECK (run_type IN ('ORIGINAL','CORRECTION','REVERSAL')),
  corrects_run_id BIGINT REFERENCES payroll_runs(id),
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','SNAPSHOT_READY','CALCULATED','VALIDATED','APPROVED','FINALIZED')),
  prepared_by TEXT,
  prepared_at TIMESTAMPTZ,
  validated_by TEXT,
  validated_at TIMESTAMPTZ,
  approved_by TEXT,
  approved_at TIMESTAMPTZ,
  finalized_by TEXT,
  finalized_at TIMESTAMPTZ,
  engine_version TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now(),
  UNIQUE (payroll_period_id, run_number)
);

CREATE TABLE payroll_run_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_run_id BIGINT NOT NULL REFERENCES payroll_runs(id) ON DELETE CASCADE,
  snapshot_id BIGINT NOT NULL REFERENCES payroll_input_snapshots(id),
  employee_id TEXT NOT NULL REFERENCES employees(id),
  legal_entity_id TEXT NOT NULL,
  calc_status TEXT NOT NULL,
  gross_sen BIGINT,
  taxable_base_sen BIGINT,
  bpjs_base_sen BIGINT,
  overtime_sen BIGINT,
  bpjs_employee_sen BIGINT,
  bpjs_employer_sen BIGINT,
  tax_sen BIGINT,
  other_deductions_sen BIGINT,
  employee_deductions_sen BIGINT,
  net_sen BIGINT,
  employer_cost_sen BIGINT,
  payroll_rule_set_id BIGINT,
  jkk_rate_version_id BIGINT,
  ter_category TEXT,
  result_payload TEXT NOT NULL,
  result_hash TEXT NOT NULL,
  snapshot_hash TEXT NOT NULL,
  calculated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (payroll_run_id, employee_id)
);

CREATE TABLE payroll_run_line_components (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_run_line_id BIGINT NOT NULL REFERENCES payroll_run_lines(id) ON DELETE CASCADE,
  sequence BIGINT NOT NULL,
  component_code TEXT NOT NULL,
  component_group TEXT NOT NULL,
  paid_by TEXT,
  basis TEXT,
  quantity TEXT,
  rate TEXT,
  formula TEXT,
  rounding_rule TEXT,
  rule_version TEXT,
  source_snapshot_field TEXT,
  amount_sen BIGINT
);

CREATE TABLE payroll_run_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_run_id BIGINT NOT NULL REFERENCES payroll_runs(id) ON DELETE CASCADE,
  from_status TEXT,
  to_status TEXT NOT NULL,
  actor TEXT NOT NULL,
  note TEXT,
  detail TEXT,
  occurred_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE payroll_payslips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_run_id BIGINT NOT NULL REFERENCES payroll_runs(id),
  payroll_run_line_id BIGINT NOT NULL REFERENCES payroll_run_lines(id),
  payroll_period_id BIGINT NOT NULL REFERENCES payroll_periods(id),
  employee_id TEXT NOT NULL REFERENCES employees(id),
  legal_entity_id TEXT NOT NULL,
  run_number BIGINT NOT NULL,
  payslip_version BIGINT NOT NULL DEFAULT 1,
  payslip_reference TEXT NOT NULL,
  document TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  line_result_hash TEXT NOT NULL,
  snapshot_hash TEXT NOT NULL,
  gross_sen BIGINT NOT NULL,
  employee_deductions_sen BIGINT NOT NULL,
  net_sen BIGINT NOT NULL,
  employer_cost_sen BIGINT NOT NULL,
  finalized_at TIMESTAMPTZ NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL,
  generated_by TEXT NOT NULL,
  UNIQUE (payroll_run_line_id),
  UNIQUE (payslip_reference)
);

CREATE TABLE payroll_adjustments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_run_id BIGINT NOT NULL REFERENCES payroll_runs(id),
  source_period_id BIGINT NOT NULL REFERENCES payroll_periods(id),
  employee_id TEXT NOT NULL REFERENCES employees(id),
  legal_entity_id TEXT NOT NULL,
  adjustment_type TEXT NOT NULL CHECK (adjustment_type IN ( 'RETRO_EARNING','RETRO_DEDUCTION','LATE_OVERTIME', 'ATTENDANCE_CORRECTION','TAX_CORRECTION','BPJS_CORRECTION', 'MANUAL_ADJUSTMENT')),
  component_code TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('CREDIT','DEBIT')),
  amount_sen BIGINT NOT NULL CHECK (amount_sen >= 0),
  overtime_minutes BIGINT,
  overtime_day_type TEXT,
  work_date DATE,
  is_taxable BIGINT NOT NULL DEFAULT 1 CHECK (is_taxable IN (0,1)),
  is_bpjs_base BIGINT NOT NULL DEFAULT 0 CHECK (is_bpjs_base IN (0,1)),
  reason TEXT NOT NULL,
  external_reference TEXT,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','APPROVED','APPLIED','VOID')),
  applied_to_run_id BIGINT REFERENCES payroll_runs(id),
  applied_at TIMESTAMPTZ,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  approved_by TEXT,
  approved_at TIMESTAMPTZ,
  voided_by TEXT,
  voided_at TIMESTAMPTZ,
  void_reason TEXT
);

CREATE TABLE payroll_payment_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_reference TEXT NOT NULL,
  payroll_period_id BIGINT NOT NULL REFERENCES payroll_periods(id),
  payroll_group_id BIGINT NOT NULL REFERENCES payroll_groups(id),
  legal_entity_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ( 'DRAFT','VALIDATED','EXPORTED','SUBMITTED', 'PAID','PARTIALLY_PAID','CANCELLED')),
  export_format TEXT,
  export_reference TEXT,
  exported_at TIMESTAMPTZ,
  exported_by TEXT,
  export_hash TEXT,
  submitted_at TIMESTAMPTZ,
  submitted_by TEXT,
  item_count BIGINT NOT NULL DEFAULT 0,
  total_amount_sen BIGINT NOT NULL DEFAULT 0,
  prepared_by TEXT,
  prepared_at TIMESTAMPTZ,
  validated_by TEXT,
  validated_at TIMESTAMPTZ,
  authorized_by TEXT,
  authorized_at TIMESTAMPTZ,
  cancelled_by TEXT,
  cancelled_at TIMESTAMPTZ,
  cancel_reason TEXT,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (batch_reference)
);

CREATE TABLE payroll_payment_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES payroll_payment_batches(id) ON DELETE CASCADE,
  payroll_period_id BIGINT NOT NULL REFERENCES payroll_periods(id),
  employee_id TEXT NOT NULL REFERENCES employees(id),
  legal_entity_id TEXT NOT NULL,
  payment_reference TEXT NOT NULL,
  amount_sen BIGINT NOT NULL,
  source_run_ids TEXT NOT NULL,
  bank_name TEXT,
  bank_account_no TEXT,
  bank_account_name TEXT,
  bank_snapshot_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ( 'PENDING','EXPORTED','SUBMITTED','PAID', 'REJECTED','FAILED','RETURNED','CANCELLED')),
  status_reason TEXT,
  bank_response_code TEXT,
  paid_at TIMESTAMPTZ,
  retry_of_item_id BIGINT REFERENCES payroll_payment_items(id),
  retry_count BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (payment_reference)
);

CREATE TABLE payroll_payment_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT REFERENCES payroll_payment_batches(id) ON DELETE CASCADE,
  payment_item_id BIGINT REFERENCES payroll_payment_items(id) ON DELETE CASCADE,
  from_status TEXT,
  to_status TEXT NOT NULL,
  actor TEXT NOT NULL,
  note TEXT,
  detail TEXT,
  occurred_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE attendance_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timesheet_entry_id BIGINT,
  employee_id TEXT NOT NULL,
  work_date DATE NOT NULL,
  legal_entity_id TEXT,
  event_type TEXT NOT NULL,
  actor_user_id BIGINT,
  actor_name TEXT,
  source TEXT,
  old_values TEXT,
  new_values TEXT,
  reason TEXT,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT kahe_now(),
  actor_role_snapshot TEXT,
  actor_entity_scope TEXT,
  permission_used TEXT,
  target_type TEXT,
  target_id BIGINT,
  correction_id BIGINT,
  exception_id BIGINT,
  reason_code TEXT,
  result TEXT,
  delta_values TEXT
);

CREATE TABLE work_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  legal_entity_id TEXT REFERENCES legal_entities(id),
  project_code TEXT REFERENCES projects(code),
  schedule_type TEXT NOT NULL DEFAULT 'CUSTOM',
  clock_in TEXT NOT NULL,
  clock_out TEXT NOT NULL,
  standard_work_minutes BIGINT NOT NULL,
  cross_midnight BIGINT NOT NULL DEFAULT 0,
  overtime_eligibility_rule TEXT NOT NULL DEFAULT 'AFTER_SHIFT_END' CHECK (overtime_eligibility_rule IN ('AFTER_SHIFT_END','AFTER_DELAY','FIXED_TIME','NOT_ELIGIBLE')),
  overtime_delay_minutes BIGINT NOT NULL DEFAULT 0,
  overtime_eligible_from TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  effective_from DATE NOT NULL,
  effective_to DATE,
  note TEXT,
  created_by TEXT,
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT kahe_now(),
  updated_by TEXT,
  updated_by_user_id BIGINT,
  updated_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE work_schedule_breaks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_schedule_id BIGINT NOT NULL REFERENCES work_schedules(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  start_time TEXT,
  end_time TEXT,
  duration_minutes BIGINT NOT NULL,
  is_paid BIGINT NOT NULL DEFAULT 0,
  sequence BIGINT NOT NULL DEFAULT 1,
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE attendance_work_patterns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  legal_entity_id TEXT REFERENCES legal_entities(id),
  project_code TEXT REFERENCES projects(code),
  pattern_type TEXT NOT NULL CHECK (pattern_type IN ('FIXED_WEEKLY','CUSTOM_WEEKLY','ROTATING_CYCLE','DATE_BASED_ROSTER')),
  cycle_length_days BIGINT,
  cycle_start_date DATE,
  repeats BIGINT NOT NULL DEFAULT 1,
  default_schedule_id BIGINT REFERENCES work_schedules(id),
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  effective_from DATE NOT NULL,
  effective_to DATE,
  note TEXT,
  created_by TEXT,
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT kahe_now(),
  updated_by TEXT,
  updated_by_user_id BIGINT,
  updated_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE attendance_pattern_days (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern_id BIGINT NOT NULL REFERENCES attendance_work_patterns(id) ON DELETE CASCADE,
  day_index BIGINT NOT NULL,
  day_status TEXT NOT NULL CHECK (day_status IN ('WORK','OFF')),
  work_schedule_id BIGINT REFERENCES work_schedules(id),
  note TEXT
);

CREATE TABLE attendance_roster_dates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern_id BIGINT REFERENCES attendance_work_patterns(id) ON DELETE CASCADE,
  employee_id TEXT REFERENCES employees(id) ON DELETE CASCADE,
  work_date DATE NOT NULL,
  day_status TEXT NOT NULL CHECK (day_status IN ('WORK','OFF')),
  work_schedule_id BIGINT REFERENCES work_schedules(id),
  note TEXT,
  created_by TEXT,
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE attendance_date_overrides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT REFERENCES employees(id) ON DELETE CASCADE,
  pattern_id BIGINT REFERENCES attendance_work_patterns(id) ON DELETE CASCADE,
  legal_entity_id TEXT REFERENCES legal_entities(id),
  work_date DATE NOT NULL,
  override_status TEXT NOT NULL CHECK (override_status IN ('WORK','OFF')),
  work_schedule_id BIGINT REFERENCES work_schedules(id),
  reason TEXT NOT NULL,
  is_active BIGINT NOT NULL DEFAULT 1,
  created_by TEXT,
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE attendance_schedule_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  legal_entity_id TEXT NOT NULL REFERENCES legal_entities(id),
  pattern_id BIGINT REFERENCES attendance_work_patterns(id),
  work_schedule_id BIGINT REFERENCES work_schedules(id),
  project_code TEXT REFERENCES projects(code),
  workfront TEXT,
  effective_from DATE NOT NULL,
  effective_to DATE,
  note TEXT,
  created_by TEXT,
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE attendance_correction_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  legal_entity_id TEXT REFERENCES legal_entities(id),
  project_code TEXT REFERENCES projects(code),
  correction_window BIGINT NOT NULL,
  window_unit TEXT NOT NULL DEFAULT 'DAYS' CHECK (window_unit IN ('DAYS','WEEKS','MONTHS')),
  allow_late_correction BIGINT NOT NULL DEFAULT 1,
  late_requires_approval BIGINT NOT NULL DEFAULT 1,
  evidence_requirement TEXT NOT NULL DEFAULT 'OPTIONAL' CHECK (evidence_requirement IN ('NONE','OPTIONAL','REQUIRED')),
  post_finalized_evidence_required BIGINT NOT NULL DEFAULT 1,
  additional_approval_required BIGINT NOT NULL DEFAULT 0,
  abnormal_duration_ratio_pct BIGINT NOT NULL DEFAULT 150,
  ot_grace_minutes BIGINT NOT NULL DEFAULT 30,
  ot_mismatch_tolerance_minutes BIGINT NOT NULL DEFAULT 15,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  effective_from DATE NOT NULL,
  effective_to DATE,
  note TEXT,
  created_by TEXT,
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT kahe_now(),
  updated_by TEXT,
  updated_by_user_id BIGINT,
  updated_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE attendance_corrections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_no TEXT UNIQUE,
  request_type TEXT NOT NULL CHECK (request_type IN ('CORRECTION','VOID')),
  timesheet_entry_id BIGINT REFERENCES timesheet_entries(id),
  employee_id TEXT NOT NULL REFERENCES employees(id),
  legal_entity_id TEXT NOT NULL REFERENCES legal_entities(id),
  work_date DATE NOT NULL,
  status TEXT NOT NULL CHECK (status IN ( 'DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','CANCELLED','APPLIED','REVERSED', 'PENDING_PAYROLL_REVIEW','PAYROLL_REJECTED','QUEUED_FOR_PAYROLL', 'VOID_REQUESTED','VOID_REVIEWED','VOID_APPROVED','VOID_REJECTED','VOIDED')),
  policy_id BIGINT REFERENCES attendance_correction_policies(id),
  policy_snapshot TEXT,
  is_late_correction BIGINT NOT NULL DEFAULT 0,
  late_reason TEXT,
  reason_code TEXT NOT NULL,
  reason_text TEXT,
  evidence_type TEXT,
  evidence_ref TEXT,
  evidence_note TEXT,
  before_values TEXT,
  proposed_values TEXT,
  after_values TEXT,
  delta_values TEXT,
  payroll_impact TEXT CHECK (payroll_impact IS NULL OR payroll_impact IN ('NO_PAYROLL_IMPACT','PAYROLL_IMPACT_OPEN_PERIOD', 'PAYROLL_IMPACT_FROZEN_PERIOD','PAYROLL_ADJUSTMENT_REQUIRED')),
  payroll_period_id BIGINT REFERENCES payroll_periods(id),
  payroll_run_id BIGINT REFERENCES payroll_runs(id),
  applied_to_source BIGINT NOT NULL DEFAULT 0,
  applied_version_no BIGINT,
  requested_by_user_id BIGINT,
  requested_by_name TEXT,
  requested_by_role TEXT,
  requested_at TIMESTAMPTZ,
  reviewed_by_user_id BIGINT,
  reviewed_by_name TEXT,
  reviewed_by_role TEXT,
  reviewed_at TIMESTAMPTZ,
  decided_by_user_id BIGINT,
  decided_by_name TEXT,
  decided_by_role TEXT,
  decided_at TIMESTAMPTZ,
  payroll_reviewed_by_user_id BIGINT,
  payroll_reviewed_by_name TEXT,
  payroll_reviewed_by_role TEXT,
  payroll_reviewed_at TIMESTAMPTZ,
  payroll_review_result TEXT,
  created_at TIMESTAMPTZ DEFAULT kahe_now(),
  updated_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE attendance_correction_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  correction_id BIGINT NOT NULL REFERENCES attendance_corrections(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  result TEXT,
  actor_user_id BIGINT,
  actor_name TEXT,
  actor_role TEXT,
  permission_used TEXT,
  reason_code TEXT,
  reason TEXT,
  from_status TEXT,
  to_status TEXT,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT kahe_now()
);

CREATE TABLE attendance_entry_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timesheet_entry_id BIGINT NOT NULL,
  employee_id TEXT NOT NULL,
  work_date DATE NOT NULL,
  legal_entity_id TEXT,
  version_no BIGINT NOT NULL,
  version_type TEXT NOT NULL CHECK (version_type IN ('ORIGINAL','CORRECTION','VOID')),
  correction_id BIGINT REFERENCES attendance_corrections(id),
  payload TEXT NOT NULL,
  applied_to_source BIGINT NOT NULL DEFAULT 1,
  is_effective BIGINT NOT NULL DEFAULT 1,
  actor_user_id BIGINT,
  actor_name TEXT,
  actor_role TEXT,
  reason_code TEXT,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT kahe_now()
);

CREATE TABLE attendance_exceptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timesheet_entry_id BIGINT REFERENCES timesheet_entries(id),
  employee_id TEXT NOT NULL,
  legal_entity_id TEXT,
  work_date DATE NOT NULL,
  exception_type TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'MEDIUM' CHECK (severity IN ('LOW','MEDIUM','HIGH')),
  status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','ASSIGNED','RESOLVED','REOPENED')),
  detail TEXT,
  correction_id BIGINT REFERENCES attendance_corrections(id),
  assigned_to_user_id BIGINT,
  assigned_to_name TEXT,
  assigned_at TIMESTAMPTZ,
  resolved_by_user_id BIGINT,
  resolved_by_name TEXT,
  resolved_by_role TEXT,
  resolved_at TIMESTAMPTZ,
  resolution_note TEXT,
  detected_at TIMESTAMPTZ NOT NULL DEFAULT kahe_now(),
  updated_at TIMESTAMPTZ DEFAULT kahe_now()
);

CREATE TABLE attendance_payroll_adjustments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  correction_id BIGINT NOT NULL REFERENCES attendance_corrections(id),
  employee_id TEXT NOT NULL REFERENCES employees(id),
  legal_entity_id TEXT NOT NULL,
  work_date DATE NOT NULL,
  source_period_id BIGINT REFERENCES payroll_periods(id),
  source_run_id BIGINT REFERENCES payroll_runs(id),
  impact_category TEXT NOT NULL,
  original_values TEXT NOT NULL,
  corrected_values TEXT NOT NULL,
  delta_work_minutes BIGINT NOT NULL DEFAULT 0,
  delta_overtime_minutes BIGINT NOT NULL DEFAULT 0,
  attendance_approval_ref TEXT,
  payroll_review_status TEXT NOT NULL DEFAULT 'PENDING' CHECK (payroll_review_status IN ('PENDING','APPROVED','REJECTED')),
  payroll_reviewed_by_user_id BIGINT,
  payroll_reviewed_by_name TEXT,
  payroll_reviewed_by_role TEXT,
  payroll_reviewed_at TIMESTAMPTZ,
  queue_status TEXT NOT NULL DEFAULT 'QUEUED' CHECK (queue_status IN ('QUEUED','PROCESSED','CANCELLED')),
  created_at TIMESTAMPTZ DEFAULT kahe_now()
);

-- express-session store (was created lazily by middleware/sqliteSessionStore.js)
CREATE TABLE sessions (
  sid TEXT PRIMARY KEY,
  sess TEXT NOT NULL,
  expires BIGINT NOT NULL
);
CREATE INDEX idx_sessions_expires ON sessions(expires);
