-- 0002_baseline_indexes.sql — DB-M1. The 125 A3 indexes (unique + partial-unique rules preserved verbatim).
CREATE INDEX idx_clients_entity ON clients(legal_entity_id);
CREATE INDEX idx_addon_scope ON worker_service_addons(legal_entity_id, client_id, project_id, addon_type);
CREATE INDEX idx_addon_effective ON worker_service_addons(addon_type, effective_from, effective_to);
CREATE INDEX idx_addon_status ON worker_service_addons(status);
CREATE UNIQUE INDEX uq_addon_open_per_scope ON worker_service_addons(addon_type, legal_entity_id, COALESCE(client_id,-1), COALESCE(project_id,-1)) WHERE effective_to IS NULL AND status = 'ACTIVE';
CREATE INDEX idx_addon_audit ON worker_service_addon_audit(addon_id, id);
CREATE INDEX idx_rate_scope ON billing_rate_cards(addon_type, legal_entity_id, client_id, project_id);
CREATE INDEX idx_rate_effective ON billing_rate_cards(effective_from, effective_to);
CREATE UNIQUE INDEX uq_rate_open_per_scope ON billing_rate_cards(addon_type, COALESCE(meal_type,'-'), legal_entity_id, COALESCE(client_id,-1), COALESCE(project_id,-1)) WHERE effective_to IS NULL AND status = 'ACTIVE';
CREATE INDEX idx_meal_plan_scope ON meal_plan_items(legal_entity_id, client_id, project_id, meal_type);
CREATE UNIQUE INDEX uq_meal_plan_open_per_scope ON meal_plan_items(meal_type, legal_entity_id, COALESCE(client_id,-1), COALESCE(project_id,-1)) WHERE effective_to IS NULL AND status = 'ACTIVE';
CREATE INDEX idx_qty_scope ON billing_quantities(legal_entity_id, client_id, project_id, billing_period);
CREATE INDEX idx_qty_type ON billing_quantities(addon_type, billing_period, verification_status);
CREATE INDEX idx_qty_employee ON billing_quantities(employee_id, billing_period);
CREATE INDEX idx_qty_run ON billing_quantities(billed_in_run_id);
CREATE UNIQUE INDEX uq_qty_live_per_service_day ON billing_quantities(addon_type, COALESCE(meal_type,'-'), legal_entity_id, COALESCE(client_id,-1), COALESCE(project_id,-1), COALESCE(employee_id,'-'), service_date, quantity_source) WHERE verification_status IN ('UNVERIFIED','VERIFIED') AND service_date IS NOT NULL;
CREATE INDEX idx_qty_audit ON billing_quantity_audit(quantity_id, id);
CREATE INDEX idx_billing_run_scope ON billing_runs(legal_entity_id, client_id, billing_period);
CREATE INDEX idx_billing_line_run ON billing_lines(billing_run_id);
CREATE INDEX idx_billing_line_type ON billing_lines(addon_type, billing_period);
CREATE UNIQUE INDEX uq_service_fee_open_per_scope ON service_fee_config(legal_entity_id, COALESCE(client_id,-1), COALESCE(project_id,-1)) WHERE effective_to IS NULL AND status = 'ACTIVE';
CREATE INDEX idx_entity_scope_user ON user_legal_entity_scope(user_id);
CREATE INDEX idx_entity_scope_entity ON user_legal_entity_scope(legal_entity_id);
CREATE INDEX idx_entity_audit_user ON entity_access_audit(user_id, id);
CREATE INDEX idx_entity_audit_outcome ON entity_access_audit(outcome, id);
CREATE INDEX idx_employees_worker_type ON employees(worker_type);
CREATE INDEX idx_employees_project ON employees(project_code);
CREATE INDEX idx_employees_status ON employees(status);
CREATE INDEX idx_employees_contract_end ON employees(contract_end);
CREATE INDEX idx_contract_history_employee ON employee_contract_history(employee_id);
CREATE INDEX idx_documents_employee ON employee_documents(employee_id);
CREATE INDEX idx_documents_expiry ON employee_documents(expiry_date);
CREATE INDEX idx_timesheet_date ON timesheet_entries(work_date);
CREATE INDEX idx_timesheet_employee ON timesheet_entries(employee_id);
CREATE INDEX idx_timesheet_overtime_status ON timesheet_entries(overtime_status);
CREATE INDEX idx_jkk_risk_class_lookup ON jkk_risk_classes(risk_class, effective_date);
CREATE INDEX idx_ter_lookup ON ptkp_ter_rates(rule_set_id, category, income_min_sen);
CREATE INDEX idx_overtime_multiplier_lookup ON overtime_multiplier_rules(rule_set_id, day_type, hour_from);
CREATE INDEX idx_payroll_assignment_employee ON employee_payroll_assignments(employee_id, effective_date);
CREATE INDEX idx_config_audit_domain ON config_audit_log(domain, record_id);
CREATE UNIQUE INDEX uq_payroll_assignment_open_per_employee ON employee_payroll_assignments(employee_id) WHERE end_date IS NULL;
CREATE UNIQUE INDEX uq_payroll_rule_set_single_active ON payroll_rule_sets(status) WHERE status = 'active';
CREATE UNIQUE INDEX uq_jkk_open_per_risk_class ON jkk_risk_classes(risk_class) WHERE end_date IS NULL;
CREATE UNIQUE INDEX uq_holiday_national_per_date ON holidays("date") WHERE scope = 'national';
CREATE INDEX idx_salary_component_lookup ON salary_components(code, effective_from);
CREATE INDEX idx_salary_component_entity ON salary_components(legal_entity_id, status);
CREATE UNIQUE INDEX uq_salary_component_open_scoped ON salary_components(code, legal_entity_id) WHERE effective_to IS NULL AND legal_entity_id IS NOT NULL;
CREATE UNIQUE INDEX uq_salary_component_open_global ON salary_components(code) WHERE effective_to IS NULL AND legal_entity_id IS NULL;
CREATE INDEX idx_emp_salary_component_employee ON employee_salary_components(employee_id, effective_from);
CREATE INDEX idx_emp_salary_component_component ON employee_salary_components(component_id);
CREATE UNIQUE INDEX uq_emp_salary_component_open ON employee_salary_components(employee_id, component_id) WHERE effective_to IS NULL;
CREATE INDEX idx_work_calendar_scope ON work_calendars(legal_entity_id, project_code, effective_from);
CREATE UNIQUE INDEX uq_work_calendar_open_code ON work_calendars(code) WHERE effective_to IS NULL;
CREATE INDEX idx_holidays_date ON holidays("date");
CREATE INDEX idx_payroll_group_entity ON payroll_groups(legal_entity_id, status);
CREATE UNIQUE INDEX uq_payroll_group_open_code ON payroll_groups(code) WHERE effective_to IS NULL;
CREATE INDEX idx_payroll_period_group_dates ON payroll_periods(payroll_group_id, period_start, period_end);
CREATE INDEX idx_payroll_period_status ON payroll_periods(status);
CREATE UNIQUE INDEX uq_payroll_period_group_cycle ON payroll_periods(payroll_group_id, period_year, period_sequence);
CREATE UNIQUE INDEX uq_payroll_period_group_start ON payroll_periods(payroll_group_id, period_start);
CREATE INDEX idx_snapshot_period ON payroll_input_snapshots(payroll_period_id, status);
CREATE INDEX idx_snapshot_employee ON payroll_input_snapshots(employee_id);
CREATE INDEX idx_snapshot_entity ON payroll_input_snapshots(legal_entity_id);
CREATE UNIQUE INDEX uq_snapshot_period_employee ON payroll_input_snapshots(payroll_period_id, employee_id);
CREATE INDEX idx_exception_period ON payroll_exceptions(payroll_period_id, severity);
CREATE INDEX idx_exception_employee ON payroll_exceptions(employee_id);
CREATE INDEX idx_exception_open ON payroll_exceptions(payroll_period_id, resolution_status);
CREATE INDEX idx_exception_entity ON payroll_exceptions(legal_entity_id);
CREATE UNIQUE INDEX uq_exception_snapshot_code ON payroll_exceptions(snapshot_id, exception_code);
CREATE INDEX idx_payroll_run_period ON payroll_runs(payroll_period_id, status);
CREATE INDEX idx_payroll_run_entity ON payroll_runs(legal_entity_id);
CREATE UNIQUE INDEX uq_payroll_run_single_finalized_original ON payroll_runs(payroll_period_id) WHERE status = 'FINALIZED' AND run_type = 'ORIGINAL';
CREATE UNIQUE INDEX uq_payroll_reversal_single ON payroll_runs(corrects_run_id) WHERE status = 'FINALIZED' AND run_type = 'REVERSAL';
CREATE INDEX idx_run_line_run ON payroll_run_lines(payroll_run_id);
CREATE INDEX idx_run_line_employee ON payroll_run_lines(employee_id);
CREATE INDEX idx_run_line_component ON payroll_run_line_components(payroll_run_line_id, sequence);
CREATE INDEX idx_run_event_run ON payroll_run_events(payroll_run_id, id);
CREATE INDEX idx_payslip_run ON payroll_payslips(payroll_run_id);
CREATE INDEX idx_payslip_employee ON payroll_payslips(employee_id, payroll_period_id);
CREATE INDEX idx_payslip_entity ON payroll_payslips(legal_entity_id);
CREATE INDEX idx_adjustment_source ON payroll_adjustments(source_run_id, status);
CREATE INDEX idx_adjustment_employee ON payroll_adjustments(employee_id, source_period_id);
CREATE INDEX idx_adjustment_applied ON payroll_adjustments(applied_to_run_id);
CREATE INDEX idx_adjustment_entity ON payroll_adjustments(legal_entity_id);
CREATE UNIQUE INDEX uq_adjustment_external_reference ON payroll_adjustments(external_reference) WHERE external_reference IS NOT NULL;
CREATE INDEX idx_payment_batch_period ON payroll_payment_batches(payroll_period_id, status);
CREATE INDEX idx_payment_batch_entity ON payroll_payment_batches(legal_entity_id);
CREATE UNIQUE INDEX uq_payment_item_live_per_batch ON payroll_payment_items(batch_id, employee_id) WHERE status != 'CANCELLED';
CREATE INDEX idx_payment_item_batch ON payroll_payment_items(batch_id, status);
CREATE INDEX idx_payment_item_employee ON payroll_payment_items(employee_id, payroll_period_id);
CREATE INDEX idx_payment_item_entity ON payroll_payment_items(legal_entity_id);
CREATE UNIQUE INDEX uq_payment_item_live_per_period ON payroll_payment_items(payroll_period_id, employee_id) WHERE status NOT IN ('REJECTED','FAILED','RETURNED','CANCELLED');
CREATE INDEX idx_payment_event_batch ON payroll_payment_events(batch_id, id);
CREATE INDEX idx_payment_event_item ON payroll_payment_events(payment_item_id, id);
CREATE INDEX idx_timesheet_entity_date ON timesheet_entries(legal_entity_id, work_date);
CREATE INDEX idx_attendance_events_entry ON attendance_events(timesheet_entry_id, id);
CREATE INDEX idx_attendance_events_entity ON attendance_events(legal_entity_id, work_date);
CREATE UNIQUE INDEX uq_work_schedule_open_scoped ON work_schedules(code, legal_entity_id) WHERE effective_to IS NULL AND legal_entity_id IS NOT NULL;
CREATE UNIQUE INDEX uq_work_schedule_open_global ON work_schedules(code) WHERE effective_to IS NULL AND legal_entity_id IS NULL;
CREATE INDEX idx_work_schedule_code ON work_schedules(code, effective_from);
CREATE INDEX idx_schedule_break ON work_schedule_breaks(work_schedule_id, sequence);
CREATE UNIQUE INDEX uq_attendance_pattern_open_scoped ON attendance_work_patterns(code, legal_entity_id) WHERE effective_to IS NULL AND legal_entity_id IS NOT NULL;
CREATE UNIQUE INDEX uq_attendance_pattern_open_global ON attendance_work_patterns(code) WHERE effective_to IS NULL AND legal_entity_id IS NULL;
CREATE UNIQUE INDEX uq_pattern_day ON attendance_pattern_days(pattern_id, day_index);
CREATE UNIQUE INDEX uq_roster_date_pattern ON attendance_roster_dates(pattern_id, work_date) WHERE pattern_id IS NOT NULL;
CREATE UNIQUE INDEX uq_roster_date_employee ON attendance_roster_dates(employee_id, work_date) WHERE employee_id IS NOT NULL;
CREATE UNIQUE INDEX uq_override_employee_date ON attendance_date_overrides(employee_id, work_date) WHERE employee_id IS NOT NULL AND is_active = 1;
CREATE UNIQUE INDEX uq_override_pattern_date ON attendance_date_overrides(pattern_id, work_date) WHERE employee_id IS NULL AND pattern_id IS NOT NULL AND is_active = 1;
CREATE UNIQUE INDEX uq_attendance_assignment_open ON attendance_schedule_assignments(employee_id) WHERE effective_to IS NULL;
CREATE INDEX idx_attendance_assignment_emp ON attendance_schedule_assignments(employee_id, effective_from);
CREATE INDEX idx_roster_dates_date ON attendance_roster_dates(work_date);
CREATE INDEX idx_overrides_date ON attendance_date_overrides(work_date);
CREATE UNIQUE INDEX uq_correction_policy_open_scoped ON attendance_correction_policies(legal_entity_id) WHERE effective_to IS NULL AND legal_entity_id IS NOT NULL;
CREATE UNIQUE INDEX uq_correction_policy_open_global ON attendance_correction_policies(code) WHERE effective_to IS NULL AND legal_entity_id IS NULL;
CREATE INDEX idx_correction_status ON attendance_corrections(status, legal_entity_id);
CREATE INDEX idx_correction_entry ON attendance_corrections(timesheet_entry_id);
CREATE INDEX idx_correction_employee ON attendance_corrections(employee_id, work_date);
CREATE INDEX idx_correction_actions ON attendance_correction_actions(correction_id, id);
CREATE INDEX idx_correction_actions_actor ON attendance_correction_actions(actor_user_id, occurred_at);
CREATE UNIQUE INDEX uq_entry_version ON attendance_entry_versions(timesheet_entry_id, version_no);
CREATE INDEX idx_entry_version_emp ON attendance_entry_versions(employee_id, work_date);
CREATE UNIQUE INDEX uq_exception_open ON attendance_exceptions(employee_id, work_date, exception_type) WHERE status IN ('OPEN','ASSIGNED','REOPENED');
CREATE INDEX idx_exception_status ON attendance_exceptions(status, legal_entity_id, work_date);
CREATE INDEX idx_payroll_adj_queue ON attendance_payroll_adjustments(queue_status, legal_entity_id);
CREATE UNIQUE INDEX uq_payroll_adj_correction ON attendance_payroll_adjustments(correction_id);
