-- 0004_data_migration_ledger.sql — DB-M1 CP4
-- Evidence of the one-way SQLite -> PostgreSQL data migration: what was loaded, from which
-- exact source file (sha256), when, by whom, and with what reconciliation result. Written in
-- the SAME transaction as the data, so a rolled-back migration leaves no ledger row either.
CREATE TABLE data_migrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_kind TEXT NOT NULL,
  source_name TEXT NOT NULL,
  source_sha256 TEXT NOT NULL,
  tool_version TEXT NOT NULL,
  tables_migrated BIGINT NOT NULL,
  rows_migrated BIGINT NOT NULL,
  content_checksum TEXT NOT NULL,
  report TEXT NOT NULL,
  migrated_by TEXT NOT NULL DEFAULT current_user,
  migrated_at TIMESTAMPTZ NOT NULL DEFAULT kahe_now()
);
