-- 0007_attendance_readiness.sql — Attendance A4 CP2
-- Attendance Period READINESS gate (approved CP2 contract). ADDITIVE: migration 0006 is untouched.
--
-- Objects: 1 table, 2 FKs, 1 index, 3 row triggers + 1 no-truncate trigger, 3 new functions,
-- and 2 CP1 functions replaced (CREATE OR REPLACE) to enable exactly:
--   REVIEW -> READY_TO_CLOSE  (only with a successful evaluation written in the same transaction)
--   READY_TO_CLOSE -> REVIEW  (controlled withdrawal, reason required)
-- Every other CP1 rule is byte-identical. No trigger on timesheet_entries. No business rows
-- (the attendance_readiness permission module is created by database/seed.js).
-- Evaluations are computed by the server (lib/attendanceReadiness.js); the database verifies
-- actor, period state, entity and policy linkage, and makes the record immutable.

CREATE TABLE attendance_readiness_evaluations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id BIGINT NOT NULL REFERENCES attendance_periods(id),
  legal_entity_id TEXT NOT NULL,
  policy_id BIGINT NOT NULL REFERENCES attendance_closing_policies(id),
  policy_version_no BIGINT NOT NULL,
  policy_as_of_date DATE NOT NULL,
  blocker_count BIGINT NOT NULL CHECK (blocker_count = 0),
  warning_count BIGINT NOT NULL CHECK (warning_count >= 0),
  informational_count BIGINT NOT NULL CHECK (informational_count >= 0),
  summary JSONB NOT NULL,
  fingerprint TEXT NOT NULL CHECK (fingerprint ~ '^[0-9a-f]{64}$'),
  engine_version TEXT NOT NULL,
  evaluated_at TIMESTAMPTZ NOT NULL,
  actor_user_id BIGINT NOT NULL,
  actor_name TEXT NOT NULL,
  actor_role TEXT NOT NULL,
  permission TEXT NOT NULL,
  txid BIGINT NOT NULL
);
CREATE INDEX idx_attendance_readiness_evaluations_period ON attendance_readiness_evaluations (period_id);

-- Guarded insert: actor, period state, entity and policy linkage are verified; actor, time and
-- transaction id are always written by the database (any supplied value is replaced).
CREATE FUNCTION kahe_rdy_guard_insert_fn() RETURNS trigger LANGUAGE plpgsql AS $fn$
DECLARE a record; p record; pol record;
BEGIN
  a := kahe_a4_actor('attendance_readiness:APPROVE');
  SELECT * INTO p FROM attendance_periods WHERE id = NEW.period_id FOR NO KEY UPDATE;
  IF NOT FOUND THEN
    PERFORM kahe_a4_raise('ATTENDANCE_READINESS_EVIDENCE_INVALID', jsonb_build_object('reason', 'PERIOD_NOT_FOUND'));
  END IF;
  IF p.status <> 'REVIEW' THEN
    PERFORM kahe_a4_raise('ATTENDANCE_READINESS_EVIDENCE_INVALID', jsonb_build_object('reason', 'PERIOD_NOT_IN_REVIEW'));
  END IF;
  IF NEW.legal_entity_id IS DISTINCT FROM p.legal_entity_id THEN
    PERFORM kahe_a4_raise('ATTENDANCE_READINESS_EVIDENCE_INVALID', jsonb_build_object('reason', 'ENTITY_MISMATCH'));
  END IF;
  SELECT * INTO pol FROM attendance_closing_policies WHERE id = NEW.policy_id;
  IF NOT FOUND THEN
    PERFORM kahe_a4_raise('ATTENDANCE_READINESS_EVIDENCE_INVALID', jsonb_build_object('reason', 'POLICY_NOT_FOUND'));
  END IF;
  IF pol.legal_entity_id <> p.legal_entity_id THEN
    PERFORM kahe_a4_raise('ATTENDANCE_READINESS_EVIDENCE_INVALID', jsonb_build_object('reason', 'POLICY_ENTITY_MISMATCH'));
  END IF;
  IF pol.version_no IS DISTINCT FROM NEW.policy_version_no THEN
    PERFORM kahe_a4_raise('ATTENDANCE_READINESS_EVIDENCE_INVALID', jsonb_build_object('reason', 'POLICY_VERSION_MISMATCH'));
  END IF;
  IF NEW.policy_as_of_date IS DISTINCT FROM p.end_date THEN
    PERFORM kahe_a4_raise('ATTENDANCE_READINESS_EVIDENCE_INVALID', jsonb_build_object('reason', 'AS_OF_MISMATCH'));
  END IF;
  IF pol.status NOT IN ('ACTIVE', 'ENDED') OR pol.effective_from > p.end_date
     OR (pol.effective_to IS NOT NULL AND pol.effective_to < p.end_date) THEN
    PERFORM kahe_a4_raise('ATTENDANCE_READINESS_EVIDENCE_INVALID', jsonb_build_object('reason', 'POLICY_NOT_COVERING'));
  END IF;
  NEW.actor_user_id := a.user_id; NEW.actor_name := a.user_name; NEW.actor_role := a.user_role;
  NEW.permission := 'attendance_readiness:APPROVE';
  NEW.evaluated_at := kahe_now();
  NEW.txid := txid_current();
  RETURN NEW;
END
$fn$;

CREATE FUNCTION kahe_rdy_append_only_fn() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  PERFORM kahe_a4_raise('A4_AUDIT_APPEND_ONLY', jsonb_build_object('table', TG_TABLE_NAME, 'operation', TG_OP));
  RETURN NULL;
END
$fn$;

CREATE FUNCTION kahe_rdy_no_truncate_fn() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  PERFORM kahe_a4_raise('A4_TRUNCATE_FORBIDDEN', jsonb_build_object('table', TG_TABLE_NAME));
  RETURN NULL;
END
$fn$;

CREATE TRIGGER trg_readiness_evaluations_guard_insert BEFORE INSERT ON attendance_readiness_evaluations
  FOR EACH ROW EXECUTE FUNCTION kahe_rdy_guard_insert_fn();
CREATE TRIGGER trg_readiness_evaluations_no_update BEFORE UPDATE ON attendance_readiness_evaluations
  FOR EACH ROW EXECUTE FUNCTION kahe_rdy_append_only_fn();
CREATE TRIGGER trg_readiness_evaluations_no_delete BEFORE DELETE ON attendance_readiness_evaluations
  FOR EACH ROW EXECUTE FUNCTION kahe_rdy_append_only_fn();
CREATE TRIGGER trg_readiness_evaluations_no_truncate BEFORE TRUNCATE ON attendance_readiness_evaluations
  FOR EACH STATEMENT EXECUTE FUNCTION kahe_rdy_no_truncate_fn();

-- ============================================================================
-- CP1 functions replaced. Bodies are the 0006 text plus ONLY the approved CP2 branches.
-- ============================================================================
CREATE OR REPLACE FUNCTION trg_attendance_periods_guard_update_fn() RETURNS trigger LANGUAGE plpgsql AS $fn$
DECLARE
  a record; v_perm text; v_reason text; v_eval text;
  v_status_changed boolean := NEW.status IS DISTINCT FROM OLD.status;
  v_details_changed boolean := NEW.start_date IS DISTINCT FROM OLD.start_date
    OR NEW.end_date IS DISTINCT FROM OLD.end_date OR NEW.label IS DISTINCT FROM OLD.label;
  v_field text;
BEGIN
  -- always immutable
  v_field := CASE
    WHEN NEW.id IS DISTINCT FROM OLD.id THEN 'id'
    WHEN NEW.legal_entity_id IS DISTINCT FROM OLD.legal_entity_id THEN 'legal_entity_id'
    WHEN NEW.created_by_user_id IS DISTINCT FROM OLD.created_by_user_id THEN 'created_by_user_id'
    WHEN NEW.created_by_name IS DISTINCT FROM OLD.created_by_name THEN 'created_by_name'
    WHEN NEW.created_by_role IS DISTINCT FROM OLD.created_by_role THEN 'created_by_role'
    WHEN NEW.created_at IS DISTINCT FROM OLD.created_at THEN 'created_at'
    WHEN NEW.reopen_count IS DISTINCT FROM OLD.reopen_count THEN 'reopen_count'
  END;
  IF v_field IS NOT NULL THEN
    PERFORM kahe_a4_raise('ATTENDANCE_PERIOD_FIELD_IMMUTABLE', jsonb_build_object('field', v_field));
  END IF;
  IF OLD.status = 'FROZEN' THEN
    PERFORM kahe_a4_raise('ATTENDANCE_PERIOD_FIELD_IMMUTABLE', jsonb_build_object('field', 'status', 'status', OLD.status));
  END IF;

  IF NOT v_status_changed THEN
    -- transition metadata may change ONLY with a status transition
    v_field := CASE
      WHEN NEW.last_transition_by_user_id IS DISTINCT FROM OLD.last_transition_by_user_id THEN 'last_transition_by_user_id'
      WHEN NEW.last_transition_by_name IS DISTINCT FROM OLD.last_transition_by_name THEN 'last_transition_by_name'
      WHEN NEW.last_transition_role IS DISTINCT FROM OLD.last_transition_role THEN 'last_transition_role'
      WHEN NEW.last_transition_permission IS DISTINCT FROM OLD.last_transition_permission THEN 'last_transition_permission'
      WHEN NEW.last_transition_reason IS DISTINCT FROM OLD.last_transition_reason THEN 'last_transition_reason'
      WHEN NEW.last_transition_at IS DISTINCT FROM OLD.last_transition_at THEN 'last_transition_at'
    END;
    IF v_field IS NOT NULL THEN
      PERFORM kahe_a4_raise('ATTENDANCE_PERIOD_FIELD_IMMUTABLE', jsonb_build_object('field', v_field));
    END IF;
    IF NOT v_details_changed THEN RETURN NEW; END IF;
    IF OLD.status <> 'OPEN' THEN
      PERFORM kahe_a4_raise('ATTENDANCE_PERIOD_DETAILS_LOCKED', jsonb_build_object('status', OLD.status));
    END IF;
    PERFORM kahe_a4_actor('attendance_period:EDIT');
    IF NEW.start_date IS DISTINCT FROM OLD.start_date OR NEW.end_date IS DISTINCT FROM OLD.end_date THEN
      PERFORM kahe_a4_period_overlap_guard(NEW.legal_entity_id, NEW.start_date, NEW.end_date, OLD.id);
    END IF;
    RETURN NEW;
  END IF;

  -- status transition: details must not change in the same statement
  IF v_details_changed THEN
    PERFORM kahe_a4_raise('ATTENDANCE_PERIOD_FIELD_IMMUTABLE', jsonb_build_object('field', 'details_during_transition'));
  END IF;
  IF (OLD.status, NEW.status) IN (('OPEN','REVIEW'), ('REVIEW','OPEN')) THEN
    v_perm := 'attendance_period:EDIT';
  ELSIF OLD.status = 'REVIEW' AND NEW.status = 'READY_TO_CLOSE' THEN
    -- A4 CP2: only with a successful readiness evaluation written in THIS transaction.
    -- Without evidence (CP1 generic path, raw SQL) the transition stays NOT_ENABLED.
    v_eval := kahe_a4_ctx('readiness_evaluation_id');
    IF v_eval IS NULL THEN
      PERFORM kahe_a4_raise('ATTENDANCE_PERIOD_TRANSITION_NOT_ENABLED', jsonb_build_object('from', OLD.status, 'to', NEW.status));
    END IF;
    IF v_eval !~ '^[0-9]+$' OR NOT EXISTS (SELECT 1 FROM attendance_readiness_evaluations ev
        WHERE ev.id = v_eval::bigint AND ev.period_id = OLD.id AND ev.txid = txid_current() AND ev.blocker_count = 0) THEN
      PERFORM kahe_a4_raise('ATTENDANCE_READINESS_EVIDENCE_INVALID', jsonb_build_object('reason', 'EVALUATION_NOT_BOUND'));
    END IF;
    v_perm := 'attendance_readiness:APPROVE';
  ELSIF OLD.status = 'READY_TO_CLOSE' AND NEW.status = 'REVIEW' THEN
    -- A4 CP2: controlled withdrawal only; any other path stays NOT_ENABLED.
    IF kahe_a4_ctx('readiness_action') IS DISTINCT FROM 'WITHDRAW' THEN
      PERFORM kahe_a4_raise('ATTENDANCE_PERIOD_TRANSITION_NOT_ENABLED', jsonb_build_object('from', OLD.status, 'to', NEW.status));
    END IF;
    v_perm := 'attendance_readiness:APPROVE';
  ELSIF (OLD.status, NEW.status) IN (('READY_TO_CLOSE','CLOSED'), ('CLOSED','REVIEW'), ('CLOSED','FROZEN')) THEN
    PERFORM kahe_a4_raise('ATTENDANCE_PERIOD_TRANSITION_NOT_ENABLED', jsonb_build_object('from', OLD.status, 'to', NEW.status));
  ELSE
    PERFORM kahe_a4_raise('ATTENDANCE_PERIOD_TRANSITION_INVALID', jsonb_build_object('from', OLD.status, 'to', NEW.status));
  END IF;
  a := kahe_a4_actor(v_perm);
  v_reason := NULLIF(btrim(COALESCE(kahe_a4_ctx('reason'), '')), '');
  IF ((OLD.status = 'REVIEW' AND NEW.status = 'OPEN') OR (OLD.status = 'READY_TO_CLOSE' AND NEW.status = 'REVIEW')) AND v_reason IS NULL THEN
    PERFORM kahe_a4_raise('ATTENDANCE_PERIOD_REASON_REQUIRED', jsonb_build_object('from', OLD.status, 'to', NEW.status));
  END IF;
  NEW.last_transition_by_user_id := a.user_id; NEW.last_transition_by_name := a.user_name;
  NEW.last_transition_role := a.user_role; NEW.last_transition_permission := v_perm;
  NEW.last_transition_reason := v_reason; NEW.last_transition_at := kahe_now();
  RETURN NEW;
END
$fn$;

CREATE OR REPLACE FUNCTION trg_attendance_periods_audit_update_fn() RETURNS trigger LANGUAGE plpgsql AS $fn$
DECLARE a record;
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO attendance_period_events (period_id, event_type, from_status, to_status, actor_user_id, actor_name,
      actor_role, permission, reason, old_values, new_values, created_at)
    VALUES (NEW.id, 'TRANSITION', OLD.status, NEW.status, NEW.last_transition_by_user_id, NEW.last_transition_by_name,
      NEW.last_transition_role, NEW.last_transition_permission, NEW.last_transition_reason,
      kahe_a4_period_snapshot(OLD),
      CASE WHEN NEW.status = 'READY_TO_CLOSE'
        THEN kahe_a4_period_snapshot(NEW) || jsonb_build_object('readiness_evaluation_id', kahe_a4_ctx('readiness_evaluation_id')::bigint)
        ELSE kahe_a4_period_snapshot(NEW) END,
      NEW.last_transition_at);
  ELSIF NEW.start_date IS DISTINCT FROM OLD.start_date OR NEW.end_date IS DISTINCT FROM OLD.end_date
        OR NEW.label IS DISTINCT FROM OLD.label THEN
    a := kahe_a4_actor('attendance_period:EDIT');
    INSERT INTO attendance_period_events (period_id, event_type, from_status, to_status, actor_user_id, actor_name,
      actor_role, permission, reason, old_values, new_values, created_at)
    VALUES (NEW.id, 'DETAILS_CHANGED', OLD.status, NEW.status, a.user_id, a.user_name, a.user_role, a.permission,
      NULLIF(btrim(COALESCE(kahe_a4_ctx('reason'), '')), ''),
      kahe_a4_period_snapshot(OLD), kahe_a4_period_snapshot(NEW), kahe_now());
  END IF;
  RETURN NULL;
END
$fn$;
